# This is a basic workflow to help you get started with Actions



# Controls when the workflow will run

  # Triggers the workflow on push or pull request events but only for the "master" branch
name: Java CI with Maven


on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    name: Build on JDK
    runs-on: windows-latest


    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
